name: Release
on:
  push:
    branches:
      - master
    paths:
      - './version.json'
  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get version from version.json
        id: get_info
        run: |
          echo "version=$(node -p "require('./version.json').version")" >> $GITHUB_ENV

      - name: Get changelog
        id: get_changelog
        run: |
          echo "changelog=$(sed -n '/## v'${version}'/,/^## v/p' CHANGELOG.md | sed '/^## v'${version}'/d' | head -n -1)" >> $GITHUB_ENV

      - name: Print Changelog
        id: print_changelog
        run: |
          echo "Changelog: ${{ env.changelog }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: v${{ env.version }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: false
